version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=300
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/packages/api/node_modules
      - /app/packages/frontend/node_modules
      - /app/packages/schemas/node_modules
